# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2019-2023 The Foundation for Public Code <info@publiccode.net>, https://standard.publiccode.net/AUTHORS

title: Standard for Public Code compliant codebases

remote_theme: publiccodenet/jekyll-theme
include:
  - "README.md"
  - "LICENSE"
  - "CODE_OF_CONDUCT.md"
